# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  Repository: repository  # github repositories
  Links: links  # 友链
  About: about  # 关于

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  links: icon-friendship
  about: icon-cup-fill

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/logo.png
  title: 光羽隹的笔记本 # 页面title
  favicon: /favicon.ico
  board: <p>好好学习，天天向上</p> # 站点公告
  copyright: true # 底部版权信息

# config
config:
  skin: theme-black # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: true # enable posts thumbnail, options: true, false
  excerpt_link: Read More

# Pagination
pagination:
  number: true
  prev: 
    alwayShow: true
  next:
    alwayShow: true

# Sidebar
sidebar: right
widgets:
  - board  
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
archive_type: 'monthly'
show_count: true

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: true
  # 微信打赏
  wechatpay:
    qrcode: images/wechatpay.png
    title: 微信支付
  # 支付宝打赏
  alipay: 
    qrcode: images/alipay.png 
    title: 支付宝

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: true  # 是否启用分享
  sites: weibo,qq,wechat  # PC端显示的分享图标
  mobile_sites: weibo,qq,qzone  # 移动端显示的分享图标

# Github
github: 
  username: francistts  # github username

# PV
pv:
  busuanzi:
    enable: true  # 不蒜子统计
  leancloud:
    enable: false  # leancloud统计
    app_id: # leancloud <AppID>
    app_key: # leancloud <AppKey>
        
# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计 

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics: 
  
# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  

rss: /atom.xml
  
# profile
profile:
  enabled: true # Whether to show profile bar
  avatar: images/Earth.png
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: 光羽隹
  author_title: 砖石搬运工程师
  author_description: java后端码农
  location: 武汉/上海, 中囯
  follow: https://github.com/francistts
  # Social Links
  social:
    links:
      # github: https://github.com/gyzyao
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills 
  skills:
    Git: ★★★☆☆
    Java: ★★★☆☆
    Spring: ★★★☆☆
    Mybatis: ★★★☆☆
    Maven: ★★★☆☆
    Mysql: ★★★☆☆
  # My Personal Links
  links:
    GitHub: https://github.com/francistts
    Gitee: https://gitee.com/tts-tech
  # My Personal Labels
  labels:
    - 后端开发
    - SSM
  # My Personal Works
  works:
    navigation:
      link: http://tts-tech.gitee.io/
      date: 2016
  # My Personal Projects
  projects:
    cofess/gulp-startpro: https://github.com/francistts/gulp-startpro
    cofess/hexo-theme-pure: https://github.com/francistts/hexo-theme-pure